"""Pure-file memory layer — zero-DB, zero-API-call persistent memory.

Inspired by Claude Code's SOUL.md architecture.  Stores memories as
plain text files in ~/.hermes/memory/, with a MEMORY.md index for
human readability and quick lookup.

Advantages over SQLite/DB-backed memory:
1. Human-readable and editable
2. Zero schema migration
3. Works with any text editor, git, grep
4. No DB lock contention
5. Transparent to users — they can see what the agent remembers
"""

import os
import re
import json
import hashlib
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Default memory directory under ~/.hermes/
_DEFAULT_MEMORY_DIR = "~/.hermes/memory"

# Maximum memory entries before cleanup
_MAX_MEMORY_ENTRIES = 500

# Memory categories for organization
_MEMORY_CATEGORIES = {
    "user": "User preferences, identity, habits",
    "project": "Project conventions, tech stack, structure",
    "task": "Ongoing tasks, TODOs, reminders",
    "error": "Errors encountered and their resolutions",
    "learning": "Things learned from user corrections",
    "context": "Session context, recent decisions",
}


class FileMemoryStore:
    """Zero-DB persistent memory store using plain text files."""

    def __init__(self, memory_dir: Optional[str] = None) -> None:
        self.memory_dir = Path(memory_dir or os.path.expanduser(_DEFAULT_MEMORY_DIR))
        self.memory_dir.mkdir(parents=True, exist_ok=True)
        self.index_file = self.memory_dir / "MEMORY.md"
        self._ensure_index()

    def _ensure_index(self) -> None:
        """Create the MEMORY.md index if it doesn't exist."""
        if not self.index_file.exists():
            _header = self._build_index_header()
            self.index_file.write_text(_header, encoding="utf-8")

    def _build_index_header(self) -> str:
        """Build the MEMORY.md index header."""
        lines = [
            "# MEMORY.md — Hermes Agent Memory Index",
            "",
            "> This file is auto-generated by the FileMemoryStore.",
            "> You can edit it manually — changes will be picked up on next load.",
            "",
            "## Categories",
            "",
        ]
        for cat, desc in _MEMORY_CATEGORIES.items():
            _cat_dir = self.memory_dir / cat
            _count = len(list(_cat_dir.glob("*.md"))) if _cat_dir.exists() else 0
            lines.append(f"- **{cat}**: {desc} ({_count} entries)")
        lines.extend([
            "",
            "## Quick Links",
            "",
        ])
        for cat in _MEMORY_CATEGORIES:
            lines.append(f"- [{cat}/]({cat}/)")
        lines.extend([
            "",
            "## Search",
            "",
            "Use `grep -r 'keyword' ~/.hermes/memory/` to search memories.",
            "",
            f"_Last updated: {datetime.now().isoformat()}_",
            "",
        ])
        return "\n".join(lines)

    def _sanitize_filename(self, key: str) -> str:
        """Convert a memory key to a safe filename."""
        # Hash long keys to keep filenames manageable
        if len(key) > 80:
            _hash = hashlib.md5(key.encode()).hexdigest()[:8]
            key = key[:60] + "_" + _hash
        # Replace unsafe characters
        safe = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", key)
        safe = safe.strip("._")
        return safe[:100] or "untitled"

    def _build_entry_content(self, content: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Build a memory entry file with YAML frontmatter."""
        meta = metadata or {}
        _now = datetime.now().isoformat()
        lines = [
            "---",
            f"created: {_now}",
            f"updated: {_now}",
            f"access_count: {meta.get('access_count', 0)}",
        ]
        if "category" in meta:
            lines.append(f"category: {meta['category']}")
        if "tags" in meta:
            lines.append(f"tags: {', '.join(meta['tags'])}")
        lines.append("---")
        lines.append("")
        lines.append(content)
        lines.append("")
        lines.append("<!-- EOF -->")
        return "\n".join(lines)

    def save(
        self,
        key: str,
        content: str,
        category: str = "context",
        tags: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Save a memory entry.

        Args:
            key: Unique identifier for this memory.
            content: The memory content.
            category: Memory category (user, project, task, error, learning, context).
            tags: Optional tags for searchability.
            metadata: Optional additional metadata.

        Returns:
            Path to the saved memory file.
        """
        _cat_dir = self.memory_dir / category
        _cat_dir.mkdir(parents=True, exist_ok=True)

        _filename = self._sanitize_filename(key) + ".md"
        _file_path = _cat_dir / _filename

        _meta = dict(metadata or {})
        _meta["category"] = category
        if tags:
            _meta["tags"] = tags

        # If file exists, preserve creation date and increment access count
        if _file_path.exists():
            _existing = _file_path.read_text(encoding="utf-8")
            _created = self._extract_frontmatter(_existing, "created")
            _access = int(self._extract_frontmatter(_existing, "access_count") or "0")
            _meta["created"] = _created or datetime.now().isoformat()
            _meta["access_count"] = _access + 1
            # Update only the timestamp, keep the rest
            _meta["updated"] = datetime.now().isoformat()

        _file_content = self._build_entry_content(content, _meta)
        _file_path.write_text(_file_content, encoding="utf-8")

        logger.debug("Memory saved: %s (%s)", key, category)
        return _file_path

    def load(self, key: str, category: Optional[str] = None) -> Optional[str]:
        """Load a memory entry by key.

        Args:
            key: The memory key.
            category: Optional category to search in.

        Returns:
            Memory content or None if not found.
        """
        _filename = self._sanitize_filename(key) + ".md"

        if category:
            _file_path = self.memory_dir / category / _filename
            if _file_path.exists():
                return self._read_content(_file_path)
            return None

        # Search all categories
        for cat_dir in self.memory_dir.iterdir():
            if cat_dir.is_dir():
                _file_path = cat_dir / _filename
                if _file_path.exists():
                    return self._read_content(_file_path)
        return None

    def _read_content(self, file_path: Path) -> str:
        """Read content from a memory file, stripping frontmatter."""
        _text = file_path.read_text(encoding="utf-8")
        # Strip YAML frontmatter
        if _text.startswith("---"):
            _parts = _text.split("---", 2)
            if len(_parts) >= 3:
                return _parts[2].strip()
        return _text.strip()

    def _extract_frontmatter(self, text: str, key: str) -> Optional[str]:
        """Extract a value from YAML frontmatter."""
        if not text.startswith("---"):
            return None
        _match = re.search(rf"^{re.escape(key)}:\s*(.+)$", text, re.MULTILINE)
        return _match.group(1).strip() if _match else None

    def search(self, query: str, category: Optional[str] = None) -> List[Tuple[str, str, str]]:
        """Search memories by content.

        Args:
            query: Search query (case-insensitive).
            category: Optional category to limit search.

        Returns:
            List of (key, category, content) tuples matching the query.
        """
        _results = []
        _query_lower = query.lower()

        _search_dirs = [self.memory_dir / category] if category else [
            d for d in self.memory_dir.iterdir() if d.is_dir()
        ]

        for _dir in _search_dirs:
            if not _dir.exists():
                continue
            for _file in _dir.glob("*.md"):
                _content = _file.read_text(encoding="utf-8")
                if _query_lower in _content.lower():
                    _key = _file.stem
                    _cat = _dir.name
                    _body = self._read_content(_file)
                    _results.append((_key, _cat, _body))

        return _results

    def list_all(self, category: Optional[str] = None) -> Dict[str, List[Dict[str, Any]]]:
        """List all memories.

        Returns:
            Dict mapping category to list of memory metadata dicts.
        """
        _result = {}
        _search_dirs = [self.memory_dir / category] if category else [
            d for d in self.memory_dir.iterdir() if d.is_dir()
        ]

        for _dir in _search_dirs:
            if not _dir.exists():
                continue
            _cat = _dir.name
            _entries = []
            for _file in _dir.glob("*.md"):
                _content = _file.read_text(encoding="utf-8")
                _entries.append({
                    "key": _file.stem,
                    "created": self._extract_frontmatter(_content, "created"),
                    "updated": self._extract_frontmatter(_content, "updated"),
                    "category": _cat,
                    "size": len(_content),
                })
            _result[_cat] = _entries

        return _result

    def delete(self, key: str, category: Optional[str] = None) -> bool:
        """Delete a memory entry.

        Args:
            key: Memory key to delete.
            category: Optional category to search in.

        Returns:
            True if deleted, False if not found.
        """
        _filename = self._sanitize_filename(key) + ".md"

        if category:
            _file_path = self.memory_dir / category / _filename
            if _file_path.exists():
                _file_path.unlink()
                logger.debug("Memory deleted: %s (%s)", key, category)
                return True
            return False

        for cat_dir in self.memory_dir.iterdir():
            if cat_dir.is_dir():
                _file_path = cat_dir / _filename
                if _file_path.exists():
                    _file_path.unlink()
                    logger.debug("Memory deleted: %s (%s)", key, cat_dir.name)
                    return True
        return False

    def cleanup_old(self, max_entries: int = _MAX_MEMORY_ENTRIES) -> int:
        """Remove oldest memories if total exceeds max_entries.

        Returns:
            Number of entries removed.
        """
        _all_files = []
        for cat_dir in self.memory_dir.iterdir():
            if cat_dir.is_dir():
                for _file in cat_dir.glob("*.md"):
                    _stat = _file.stat()
                    _all_files.append((_stat.st_mtime, _file))

        if len(_all_files) <= max_entries:
            return 0

        # Sort by modification time (oldest first)
        _all_files.sort(key=lambda x: x[0])
        _to_remove = len(_all_files) - max_entries
        _removed = 0

        for _mtime, _file in _all_files[:_to_remove]:
            try:
                _file.unlink()
                _removed += 1
            except OSError:
                pass

        logger.info("Memory cleanup: removed %d old entries", _removed)
        return _removed

    def get_stats(self) -> Dict[str, Any]:
        """Return memory store statistics."""
        _total_files = 0
        _total_size = 0
        _by_category = {}

        for cat_dir in self.memory_dir.iterdir():
            if cat_dir.is_dir():
                _files = list(cat_dir.glob("*.md"))
                _count = len(_files)
                _size = sum(f.stat().st_size for f in _files)
                _total_files += _count
                _total_size += _size
                _by_category[cat_dir.name] = {"count": _count, "size": _size}

        return {
            "total_entries": _total_files,
            "total_size_bytes": _total_size,
            "memory_dir": str(self.memory_dir),
            "by_category": _by_category,
        }
